### ISSUE TITLE
Match parameters

### ISSUE THREAD

**Issue by karaeren** [gamelocker/battlerite-docs#18]
I'm using endpoint like this;

`https://api.dc01.gamelockerapp.com/shards/global/matches?sort=-createdAt&page[limit]=20&filter[playerIds]=XXX`

But it doesn't give matches that are at least 15 minutes old. Can I make it receive matches that are just finished with filters? I tried createdAt-start/end but couldn't achieve anything.

**Comment by jaloisi834** [comment]
The newest matches that have already been processed by the API will be returned when using `sort=-createdAt` (descending order) without a `filter[createdAt-start]` (default is now() - 28 days) or `filter[createdAt-end]` (default is now()) time specified just like you have shown in your example. Unfortunately, matches that have recently been completed probably haven't been fully processed by the API yet, so the newest of the new matches may not be available for some time. 

If possible, please try to submit questions/bugs through the "report a bug" widget on the [developer portal](https://developer.battlerite.com) going forward. It helps us keep things organized, and we really appreciate it!
