### ISSUE TITLE
Players' stats mapping

### ISSUE THREAD

**Issue by Tenes** [gamelocker/battlerite-docs#19]
Hello guys, first of all thanks for the awesome api you made!
But i have a big unanswered question:
What does all the number in the player's stats refers to?
I can retro engineer to find that 12011 represents the game won with Poloma, but it's a really painstacking thing to do with all those values...

**Comment by jaloisi834** [comment]
Great question! You can find all of the mapping files for those values [here](https://github.com/gamelocker/battlerite-assets) by game version.

If possible, please try to submit questions/bugs through the "report a bug" widget on the [developer portal](https://developer.battlerite.com) going forward. It helps us keep things organized, and we really appreciate it!

**Comment by Tenes** [comment]
I was talking about those datas: 
![image](https://user-images.githubusercontent.com/23052453/35975724-04aeccec-0cde-11e8-83dd-806fe16e4464.png)

I guess i'll submit my question to the widget
