### ISSUE TITLE
filter[gameMode] Misleading

### ISSUE THREAD

**Issue by hpopp** [gamelocker/battlerite-docs#2]
In the query parameters table, the `filter[gameMode]` description is misleading.
```
Filter by gameMode Usage: filter[gameMode]=casual,ranked,…
```

Both `casual` and `ranked` return 404 responses. Using a value of `1733162751` works, but currently every match on the API uses that mode, so it doesn't actually filter anything.

**Comment by jaloisi834** [comment]
Thanks for bringing this to our attention. We have decided to remove the `gameMode` and `teamName` filters from that section until they are working properly to avoid confusion.

**Comment by onethirtyfive** [comment]
:+1: to getting this working. Project I'm working on is a non-starter without filtering by `gameMode`. Thank you!
