### ISSUE TITLE
Champion data 

### ISSUE THREAD

**Issue by aarhusgregersen** [gamelocker/battlerite-docs#22]
Is there no way to pull champion data, or find corresponding information about champions?

If you pull data using the `player` call (example: `https://api.dc01.gamelockerapp.com/shards/global/players/786946724437581824`), it returns an array of stats.

However these stats are just numbers, and I'm unsure what they represent. I would guess champions from 1 through 100, and something else for the numbers of 10.000+.
I don't know what though.
Is it possible to document this, so it is possible to translate it into Champion names etc. when building an application? 

Let me know what I can do to help!

Best

**Comment by jsmienk** [comment]
Champion data can be found in the assets repo: https://github.com/gamelocker/battlerite-assets.
Look for files called stackables.json and gameplay.json.
gameplay.json will contain most champion data (EX abilities and cooldowns are missing).
stackables.json contains all cosmetics, but also the stats (numbers in the player response) you are referring to.
Hope I could help.

Jeroen

**Comment by aarhusgregersen** [comment]
Awesome!

That helped a lot, at least in navigating what is what. Thanks :-) 
Is that repository purely for documentation or is there a seperate API for these assets? 

If so, where can I find the endpoints?

**Comment by jsmienk** [comment]
I have not found an API. I package the files (images and the .json files I mentioned earlier) with my app.

**Comment by aarhusgregersen** [comment]
That makes sense, however it does require that you regularly pay attention and update the app.

Anyhoo, that's a concern for the future. Thanks so much for the help, I'll close this one out :-)

**Comment by jsmienk** [comment]
Unfortunately, yes. Let me know when you find an alternative that doesn't require me to manually update the app! (:
